version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: book_db
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - book_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  book_network:
    driver: bridge